# Generated by Django 2.2.4 on 2019-08-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perspectiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Perspectivas',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('perspectiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspectivas', to='planodeacao.Perspectiva')),
            ],
            options={
                'verbose_name_plural': 'Objetivos Estratégicos',
            },
        ),
        migrations.CreateModel(
            name='AcoesOrcamentarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=50)),
                ('prioridade', models.IntegerField()),
                ('objetivoestrategico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_estratégicos', to='planodeacao.ObjetivoEstrategico')),
            ],
            options={
                'verbose_name_plural': 'Ações Orçamentárias',
            },
        ),
    ]
