# Generated by Django 2.2.4 on 2019-08-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodeacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezadeDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrica', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Natureza de Despesas',
            },
        ),
    ]
