# Generated by Django 2.2.4 on 2019-08-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planodeacao', '0002_naturezadedespesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoesorcamentarias',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='naturezadedespesa',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='AquisicoesOrcamentarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaodaaquisicao', models.TextField(max_length=200)),
                ('tipo', models.BooleanField(choices=[(False, 'Capital'), (True, 'Custeio')], verbose_name='Tipo:')),
                ('quantidade', models.IntegerField()),
                ('valorunitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pgc', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], verbose_name='PGC:')),
                ('acaoorcamentaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_orcamentarias', to='planodeacao.AcoesOrcamentarias')),
                ('naturezadedespesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natureza_de_despesa', to='planodeacao.NaturezadeDespesa')),
            ],
            options={
                'verbose_name_plural': 'Aquisições Orçamentárias',
            },
        ),
    ]
